export const homePageData = {
  data() {
    return {
      tableDataOne: [
        {
          risk_asset: "XXXXXX(1.2.3.4)",
          victim_ip: "1.2.3.4",
          branch_name: "XXXXXX",
          victim_classify1_id: 1,
          risk_level: 1,
          threat_descs: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          record_time: "2024-03-02 06:45:46",
          status: 0,
          victim_asset_id: 350103214430,
          src_asset_id: null,
          dst_asset_id: 350103214430,
          branch_id: 350,
          src_branch_id: null,
          dst_branch_id: 350,
          tag: [
            {
              hole_id: 2026008,
              threat_id: "0",
              event_desc: "XXXXXXXXXXXXXXXXXXXXXXX",
              status: 0,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
            {
              hole_id: 2026009,
              threat_id: "0",
              event_desc: "XXXXXXXXXXXXXXXXXXXXXX",
              status: 3,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
            {
              hole_id: 2026009,
              threat_id: "0",
              event_desc: "XXXXX",
              status: 2,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
          ],
          victim_asset_gtoup_id: 350,
          attack_ip: "4.3.2.1",
        },
        {
          risk_asset: "XXXXXX(1.2.3.4)",
          victim_ip: "1.2.3.4",
          branch_name: "XXXXXX",
          victim_classify1_id: 1,
          risk_level: 2,
          threat_descs: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          record_time: "2024-03-02 06:45:46",
          status: 0,
          victim_asset_id: 350103214430,
          src_asset_id: null,
          dst_asset_id: 350103214430,
          branch_id: 350,
          src_branch_id: null,
          dst_branch_id: 350,
          tag: [
            {
              hole_id: 2026008,
              threat_id: "0",
              event_desc: "XXXXXXXXXXXXXXXX",
              status: 3,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
            {
              hole_id: 2026009,
              threat_id: "0",
              event_desc: "XXXXXXXXXXXXXXXXXXXXXXXX",
              status: 3,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
            {
              hole_id: 2026009,
              threat_id: "0",
              event_desc: "XXXXX",
              status: 3,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
          ],
          victim_asset_gtoup_id: 350,
          attack_ip: "4.3.2.1",
        },
        {
          risk_asset: "XXXXXX(1.2.3.4)",
          victim_ip: "1.2.3.4",
          branch_name: "XXXXXX",
          victim_classify1_id: 1,
          risk_level: 2,
          threat_descs: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          record_time: "2024-03-02 06:45:46",
          status: 0,
          victim_asset_id: 350103214430,
          src_asset_id: null,
          dst_asset_id: 350103214430,
          branch_id: 350,
          src_branch_id: null,
          dst_branch_id: 350,
          tag: [
            {
              hole_id: 2026008,
              threat_id: "0",
              event_desc: "XXXXXXX",
              status: 3,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
            {
              hole_id: 2026009,
              threat_id: "0",
              event_desc: "XXXXXXXXXXXXXXXXXXXX",
              status: 3,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
            {
              hole_id: 2026009,
              threat_id: "0",
              event_desc: "XXXXX",
              status: 2,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
          ],
          victim_asset_gtoup_id: 350,
          attack_ip: "4.3.2.1",
        },
        {
          risk_asset: "XXXXXX(1.2.3.4)",
          victim_ip: "1.2.3.4",
          branch_name: "XXXXXX",
          victim_classify1_id: 1,
          risk_level: 1,
          threat_descs: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          record_time: "2024-03-02 06:45:46",
          status: 0,
          victim_asset_id: 350103214430,
          src_asset_id: null,
          dst_asset_id: 350103214430,
          branch_id: 350,
          src_branch_id: null,
          dst_branch_id: 350,
          tag: [
            {
              hole_id: 2026008,
              threat_id: "0",
              event_desc: "XXXXXXXXXXXXXXXXXXXXXX",
              status: 0,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
            {
              hole_id: 2026009,
              threat_id: "0",
              event_desc: "XXXXXX",
              status: 3,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
            {
              hole_id: 2026009,
              threat_id: "0",
              event_desc: "XXXXX",
              status: 2,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
          ],
          victim_asset_gtoup_id: 350,
          attack_ip: "4.3.2.1",
        },
        {
          risk_asset: "XXXXXX(1.2.3.4)",
          victim_ip: "1.2.3.4",
          branch_name: "XXXXXX",
          victim_classify1_id: 1,
          risk_level: 3,
          threat_descs: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          record_time: "2024-03-02 06:45:46",
          status: 0,
          victim_asset_id: 350103214430,
          src_asset_id: null,
          dst_asset_id: 350103214430,
          branch_id: 350,
          src_branch_id: null,
          dst_branch_id: 350,
          tag: [
            {
              hole_id: 2026008,
              threat_id: "0",
              event_desc: "XXXXXXXXXXXXXXXXXX",
              status: 0,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
            {
              hole_id: 2026009,
              threat_id: "0",
              event_desc: "XXXXXXXXXXXXXX",
              status: 3,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
            {
              hole_id: 2026009,
              threat_id: "0",
              event_desc: "XXXXXXXXXXXXXXXX",
              status: 3,
              record_time: "2024-03-02 06:45:46",
              reliability: 3,
              level: 2,
              url: "/XXX/XXX",
            },
          ],
          victim_asset_gtoup_id: 350,
          attack_ip: "4.3.2.1",
        },
      ],
      tableDataTwo: [
        {
          createTime: "2024-03-07 05:02:00",
          name: "XXXXXXXXXXXXXXXXXXXXXXXXXX",
          type: 1,
        },
        {
          createTime: "2024-03-07 05:02:00",
          name: "XXXXXXXXXXXXXXXXXXXXXXXXXX",
          type: 1,
        },
        {
          createTime: "2024-03-07 05:02:00",
          name: "XXXXXXXXXXXXXXXXXXXXXXXXXX",
          type: 1,
        },
        {
          createTime: "2024-03-07 05:02:00",
          name: "XXXXXXXXXXXXXXXXXXXXXXXXXX",
          type: 1,
        },
        {
          createTime: "2024-03-07 05:02:00",
          name: "XXXXXXXXXXXXXXXXXXXXXXXXXX",
          type: 1,
        },
      ],
      countRanking: [
        {
          id: 1,
          name: "XXXXXX",
          count: 3,
          percentage: 30,
        },
        {
          id: 2,
          name: "XXXXXX",
          count: 5,
          percentage: 50,
        },
        {
          id: 3,
          name: "XXXXXX",
          count: 9,
          percentage: 90,
        },
        {
          id: 4,
          name: "XXXXXX",
          count: 6,
          percentage: 60,
        },
        {
          id: 5,
          name: "XXXXXX",
          count: 7,
          percentage: 70,
        },
      ],
      gaugeData: {},
      pieDataOne: {},
      pieDataTwo: { data: [] },
      lineData: {},
    };
  },
  mounted() {
    this.$nextTick(() => {
      this.gaugeData = {};
      this.lineData = {};
      this.pieDataOne = {
        pieData: [
          { value: 20, name: "极高", itemStyle: { color: "#1a6dea" } },
          { value: 100, name: "高", itemStyle: { color: "#337ded" } },
          { value: 80, name: "中", itemStyle: { color: "#669ef1" } },
          { value: 120, name: "低", itemStyle: { color: "#80aef4" } },
        ],
        count: 320,
        msg: "XXXXXX",
      };
      this.pieDataTwo.data = [
        {
          name: "AAAA",
          value: 83843,
        },
        {
          name: "BBBB",
          value: 19833,
        },
        {
          name: "CCCC",
          value: 19066,
        },
        {
          name: "DDDD",
          value: 9063,
        },
        {
          name: "EEEE",
          value: 8816,
        },
        {
          name: "FFFF",
          value: 5537,
        },
        {
          name: "GGGG",
          value: 1177,
        },
        {
          name: "HHHH",
          value: 361,
        },
        {
          name: "IIII",
          value: 41,
        },
        {
          name: "JJJJ",
          value: 40,
        },
        {
          name: "KKKK",
          value: 35,
        },
        {
          name: "LLLL",
          value: 30,
        },
        {
          name: "MMMM",
          value: 3,
        },
      ];
    });
  },
};
